---
blank_issues_enabled: false
contact_links:
  - name: Advent Of Code Community Support
    url: https://github.com/Hekkfern/advent-of-code/discussions
    about: Please ask and answer questions here.
