name: Unit Tests
run-name: Execute the unit tests of all the projects

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.2.2
        id: installpackages
        with:
          packages: ccache cppcheck
          version: 1.0
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: "${{ github.workspace }}/extern/vcpkg"
          vcpkgJsonGlob: "${{ github.workspace }}/vcpkg.json"
      - name: Run CMake+vcpkg+Ninja+CTest to generate/build/test.
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          configurePreset: "linux-x64-release"
          configurePresetAdditionalArgs: ['-DGENERATE_PROJECTS=UNITTESTS']
          buildPreset: "linux-x64-release"
          testPreset: "linux-x64-release"
        env:
          VCPKG_FORCE_SYSTEM_BINARIES: 1
