name: Unit Tests
run-name: Execute the unit tests of all the projects in Ubuntu

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    strategy:
      matrix:
        preset:
          [linux-x64-release, linux-x64-asan, linux-x64-tsan, linux-x64-lsan, linux-x64-ubsan]
    runs-on: ubuntu-22.04
    steps:
      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1.2.2
        id: installpackages
        with:
          packages: cppcheck ninja-build
          version: 1.0
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: "${{ github.workspace }}/extern/vcpkg"
          vcpkgJsonGlob: "${{ github.workspace }}/vcpkg.json"
      - name: Configure CMake project
        id: configurecmake
        run: cmake -S . --preset ${{ matrix.preset }} -DGENERATE_PROJECTS=UNITTESTS
      - name: Build CMake project
        id: buildcmake
        run: cmake --build --preset ${{ matrix.preset }} -j
      - name: Run CTest
        id: runctest
        run: ctest --preset ${{ matrix.preset }} -j
